### ISSUE TITLE
[question] filename.model generation

### ISSUE THREAD

**Issue by chris-aeviator** [gurtejrehal/FALCON---AI-Data-Crawler#15]
Could you please explain how the `filename.model` is created/ trained? Is the code part of this repository?

EDIT:

is it correct that ´filename.model´ is only used to classify images?

**Comment by gurtejrehal** [comment]
Whenever you create a model using machine learning algorithms, It is not necessary that you train your model everytime before you predict something.

You can simply save your existing model into a .model file and simply reuse it whenever you like. Its just like calling a function with different parameters.

Keras gives you this ability to save it into a .model file and use it vice versa.

PS: you can have any-name.model,  whatever you like.

**Comment by chris-aeviator** [comment]
@gurtejrehal yes thank you - I am aware of that, I was just interested how the model is trained. If I want to use this system I want to be able to fine tune it to my specific task. Looking at your code it seems that you are using Inception-v3 to predict the category of an image which is anyways outside of my usecase. Thank you.
